<section class="page-header"><div><span class="eyebrow">Visitor</span><h1><?=e((string)($visitor['full_name']??'Visitor'))?></h1><p>Visitor profile, identification and current access status.</p></div><div class="page-actions"><a class="btn btn-primary" href="<?=e(url('visit-create.php?visitor_id='.rawurlencode((string)$id)))?>"><i class="fa-solid fa-calendar-plus"></i> Create visit</a><a class="btn btn-secondary" href="<?=e(url('visitor-edit.php?id='.rawurlencode((string)$id)))?>"><i class="fa-solid fa-pen"></i> Edit visitor</a><a class="btn btn-secondary" data-back href="<?=e(url('visitors.php'))?>"><i class="fa-solid fa-arrow-left"></i> Back</a></div></section>
<?php if($error): ?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<?php if($visitor): $blacklisted=!empty($visitor['blacklisted']); ?>
<section class="content-card"><?php if(!empty($visitor['photo_ref'])): ?><div class="detail-media"><img src="<?=e((string)$visitor['photo_ref'])?>" alt="<?=e((string)($visitor['full_name']??'Visitor'))?>"></div><?php endif;?><div class="card-header detail-header"><div><h2>Visitor information</h2><p>Data is loaded from the current tenant database.</p></div><span class="status-badge <?=$blacklisted?'status-rejected':'status-approved'?>"><?=e($visitor['status']??'Unknown')?></span></div>
<dl class="detail-list"><?php foreach([
 'Phone'=>$visitor['phone']??'—','Email'=>$visitor['email']??'—','ID type'=>$visitor['id_type_name']??'—','ID number'=>$visitor['id_number']??'—',
 'Company'=>$visitor['company_name']??'—','Source'=>$visitor['source']??'—','Notes'=>$visitor['notes']??'—','Created'=>$visitor['created_at']??'—'
] as $k=>$v):?><div><dt><?=e($k)?></dt><dd><?=e((string)$v)?></dd></div><?php endforeach;?></dl>
<?php if($blacklisted&& !empty($visitor['blacklist_reason'])):?><div class="alert alert-warning"><?=e((string)$visitor['blacklist_reason'])?></div><?php endif;?>
<div class="form-actions">
<?php if(!$blacklisted): ?><form method="post" action="<?=e(url('visitor-blacklist.php'))?>" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="id" value="<?=e((string)$id)?>"><input type="hidden" name="blacklisted" value="1"><div class="field"><label for="reason">Blacklist reason</label><input id="reason" name="reason" required maxlength="255" placeholder="Reason for restricting this visitor"></div><button class="btn btn-danger" data-loading-label="Updating..."><span data-button-label>Blacklist visitor</span></button></form>
<?php else: ?><form method="post" action="<?=e(url('visitor-blacklist.php'))?>" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="id" value="<?=e((string)$id)?>"><input type="hidden" name="blacklisted" value="0"><button class="btn btn-secondary" data-loading-label="Updating..."><span data-button-label>Remove from blacklist</span></button></form><?php endif;?>
</div></section>
<?php endif;?>
