package visitors

import (
    "context"
    "errors"
    "log"
    "net/http"
    "strconv"
    "strings"

    "gatepass/internal/httpx"
    "gatepass/internal/reqctx"
    "gatepass/internal/rbac"
)

type Handler struct{ svc *Service; idTypes *IDTypeRepository; companies *CompanyRepository }
func NewHandler(svc *Service,idTypes *IDTypeRepository,companies *CompanyRepository)*Handler{return &Handler{svc:svc,idTypes:idTypes,companies:companies}}
func tenantRequest(w http.ResponseWriter,r *http.Request)(int64,bool){t,ok:=reqctx.TenantFromContext(r.Context());if !ok{httpx.WriteError(w,httpx.ErrAuthRequired);return 0,false};return t.ID,true}
func(h *Handler)visitorDTO(ctx context.Context,v *Visitor)DTO{d:=ToDTO(v);if t,err:=h.idTypes.ByID(ctx,v.IDTypeID);err==nil{d.IDTypeName=t.Name};if v.CompanyID!=nil{if c,err:=h.companies.ByID(ctx,*v.CompanyID);err==nil{d.CompanyName=c.Name}};return d}
func visitorStatusOptions()[]map[string]string{return []map[string]string{{"value":string(StatusActive),"label":"Active"},{"value":string(StatusBlacklisted),"label":"Blacklisted"}}}
func(h *Handler)Create(w http.ResponseWriter,r *http.Request){tenantID,ok:=tenantRequest(w,r);if !ok{return};claims,ok:=reqctx.ClaimsFromContext(r.Context());if !ok{httpx.WriteError(w,httpx.ErrAuthRequired);return};var in CreateInput;if !httpx.DecodeJSON(w,r,&in){return};in.FirstName=strings.TrimSpace(in.FirstName);in.LastName=strings.TrimSpace(in.LastName);if in.FirstName==""||in.LastName==""||in.IDTypeID<1{httpx.WriteError(w,httpx.ErrValidation.WithMessage("first_name, last_name and id_type_id are required"));return};v,err:=h.svc.Create(r.Context(),tenantID,in,claims.UserID);if err!=nil{writeServiceError(w,err);return};httpx.WriteJSON(w,http.StatusCreated,h.visitorDTO(r.Context(),v))}
func(h *Handler)Get(w http.ResponseWriter,r *http.Request){tenantID,ok:=tenantRequest(w,r);if !ok{return};id,err:=parseIDParam(r);if err!=nil{httpx.WriteError(w,httpx.ErrNotFound);return};v,err:=h.svc.Get(r.Context(),tenantID,id);if err!=nil{writeServiceError(w,err);return};if !h.canAccessVisitor(r.Context(),v){httpx.WriteError(w,httpx.ErrForbidden);return};httpx.WriteJSON(w,http.StatusOK,h.visitorDTO(r.Context(),v))}
func(h *Handler)List(w http.ResponseWriter,r *http.Request){tenantID,ok:=tenantRequest(w,r);if !ok{return};var f ListFilter;q:=r.URL.Query();if s:=q.Get("status");s!=""{st:=Status(s);f.Status=&st};if c:=q.Get("company_id");c!=""{if n,err:=strconv.ParseInt(c,10,64);err==nil&&n>0{f.CompanyID=&n}};if b:=q.Get("blacklisted");b!=""{if v,err:=strconv.ParseBool(b);err==nil{f.Blacklisted=&v}};f.Search=strings.TrimSpace(q.Get("q"));claims,ok:=reqctx.ClaimsFromContext(r.Context());if !ok{httpx.WriteError(w,httpx.ErrAuthRequired);return};if d,ok:=rbac.DecisionFromContext(r.Context());ok&&d.Scope==rbac.ScopeOwn{f.CreatedBy=&claims.UserID};p:=httpx.ParsePagination(r);items,total,err:=h.svc.List(r.Context(),tenantID,f,p);if err!=nil{log.Printf("VISITOR LIST FAILED: %v",err);httpx.WriteError(w,httpx.ErrInternal);return};dtos:=make([]DTO,0,len(items));for i:=range items{dtos=append(dtos,h.visitorDTO(r.Context(),&items[i]))};httpx.WriteJSON(w,http.StatusOK,map[string]any{"items":dtos,"limit":p.Limit,"offset":p.Offset,"meta":map[string]any{"total":total,"statuses":visitorStatusOptions()}})}
func(h *Handler)Update(w http.ResponseWriter,r *http.Request){tenantID,ok:=tenantRequest(w,r);if !ok{return};claims,ok:=reqctx.ClaimsFromContext(r.Context());if !ok{httpx.WriteError(w,httpx.ErrAuthRequired);return};id,err:=parseIDParam(r);if err!=nil{httpx.WriteError(w,httpx.ErrNotFound);return};existing,err:=h.svc.Get(r.Context(),tenantID,id);if err!=nil{writeServiceError(w,err);return};if !h.canAccessVisitor(r.Context(),existing){httpx.WriteError(w,httpx.ErrForbidden);return};var in UpdateInput;if !httpx.DecodeJSON(w,r,&in){return};v,err:=h.svc.Update(r.Context(),tenantID,id,in,claims.UserID);if err!=nil{writeServiceError(w,err);return};httpx.WriteJSON(w,http.StatusOK,h.visitorDTO(r.Context(),v))}
func(h *Handler)SetBlacklist(w http.ResponseWriter,r *http.Request){tenantID,ok:=tenantRequest(w,r);if !ok{return};claims,ok:=reqctx.ClaimsFromContext(r.Context());if !ok{httpx.WriteError(w,httpx.ErrAuthRequired);return};id,err:=parseIDParam(r);if err!=nil{httpx.WriteError(w,httpx.ErrNotFound);return};v,err:=h.svc.Get(r.Context(),tenantID,id);if err!=nil{writeServiceError(w,err);return};if !h.canAccessVisitor(r.Context(),v){httpx.WriteError(w,httpx.ErrForbidden);return};var in BlacklistInput;if !httpx.DecodeJSON(w,r,&in){return};if in.Blacklisted&&(in.Reason==nil||strings.TrimSpace(*in.Reason)==""){httpx.WriteError(w,httpx.ErrValidation.WithMessage("reason is required when blacklisting a visitor"));return};if err:=h.svc.SetBlacklist(r.Context(),tenantID,id,in,claims.UserID);err!=nil{writeServiceError(w,err);return};v,err=h.svc.Get(r.Context(),tenantID,id);if err!=nil{writeServiceError(w,err);return};httpx.WriteJSON(w,http.StatusOK,h.visitorDTO(r.Context(),v))}
func(h *Handler)ListIDTypes(w http.ResponseWriter,r *http.Request){if _,ok:=tenantRequest(w,r);!ok{return};items,err:=h.idTypes.List(r.Context(),r.URL.Query().Get("all")!="true");if err!=nil{httpx.WriteError(w,httpx.ErrInternal);return};out:=make([]IDTypeDTO,0,len(items));for i:=range items{out=append(out,IDTypeToDTO(&items[i]))};httpx.WriteJSON(w,http.StatusOK,out)}
func(h *Handler)GetIDType(w http.ResponseWriter,r *http.Request){if _,ok:=tenantRequest(w,r);!ok{return};id,err:=parseIDParam(r);if err!=nil{httpx.WriteError(w,httpx.ErrNotFound);return};t,err:=h.idTypes.ByID(r.Context(),id);if err!=nil{httpx.WriteError(w,httpx.ErrNotFound);return};httpx.WriteJSON(w,http.StatusOK,IDTypeToDTO(t))}
func parseIDParam(r *http.Request)(int64,error){id,err:=strconv.ParseInt(r.PathValue("id"),10,64);if err!=nil||id<1{return 0,errors.New("invalid id")};return id,nil}
func writeServiceError(w http.ResponseWriter,err error){switch{case errors.Is(err,ErrNotFound),errors.Is(err,ErrIDTypeNotFound),errors.Is(err,ErrCompanyNotFound):httpx.WriteError(w,httpx.ErrNotFound);case errors.Is(err,ErrInvalidIDType):httpx.WriteError(w,httpx.ErrValidation.WithMessage("id_type_id is invalid or inactive"));case errors.Is(err,ErrInvalidCompany):httpx.WriteError(w,httpx.ErrValidation.WithMessage("company_id is invalid or inactive"));case errors.Is(err,ErrIDNumberRequired):httpx.WriteError(w,httpx.ErrValidation.WithMessage("id_number is required for this id type"));case errors.Is(err,ErrDuplicateIDNumber):httpx.WriteError(w,httpx.AppError{Code:"duplicate_id_number",Message:"this ID document is already registered",Status:http.StatusConflict});case errors.Is(err,ErrPreRegistrationDisabled):httpx.WriteError(w,httpx.AppError{Code:"pre_registration_disabled",Message:"pre-registration is not enabled for this tenant",Status:http.StatusForbidden});case errors.Is(err,ErrCompanyNameTaken):httpx.WriteError(w,httpx.AppError{Code:"company_name_taken",Message:"a company with this name already exists",Status:http.StatusConflict});default:httpx.WriteError(w,httpx.ErrInternal)}}
func(h *Handler)canAccessVisitor(ctx context.Context,v *Visitor)bool{d,ok:=rbac.DecisionFromContext(ctx);if !ok||d.Scope==rbac.ScopeNone||d.Scope==rbac.ScopeAll{return true};if d.Scope!=rbac.ScopeOwn||v.CreatedBy==nil{return false};claims,ok:=reqctx.ClaimsFromContext(ctx);return ok&&*v.CreatedBy==claims.UserID}
func(h *Handler)IdentityMatches(w http.ResponseWriter,r *http.Request){tenantID,ok:=tenantRequest(w,r);if !ok{return};q:=r.URL.Query();idTypeID,_:=strconv.ParseInt(q.Get("id_type_id"),10,64);idNumber:=strings.TrimSpace(q.Get("id_number"));phone:=strings.TrimSpace(q.Get("phone"));email:=strings.TrimSpace(q.Get("email"));if idNumber==""&&phone==""&&email==""{httpx.WriteJSON(w,http.StatusOK,map[string]any{"items":[]IdentityMatch{}});return};items,err:=h.svc.IdentityMatches(r.Context(),tenantID,idTypeID,idNumber,phone,email);if err!=nil{httpx.WriteError(w,httpx.ErrInternal);return};out:=make([]IdentityMatch,0,len(items));for i:=range items{d:=h.visitorDTO(r.Context(),&items[i]);out=append(out,IdentityMatch{ID:d.ID,FullName:d.FullName,IDTypeID:d.IDTypeID,IDNumber:d.IDNumber,Phone:d.Phone,Email:d.Email,CompanyName:d.CompanyName,Status:d.Status,Blacklisted:d.Blacklisted})};httpx.WriteJSON(w,http.StatusOK,map[string]any{"items":out})}
