<section class="page-header"><div><span class="eyebrow">Administration</span><h1>Create user</h1><p>Create a tenant user and assign their role.</p></div><a class="btn btn-secondary" href="<?=e(url('users.php'))?>">Back</a></section>
<?php if($errors):?><div class="alert alert-danger"><div><?php foreach($errors as $x):?><div><?=e($x)?></div><?php endforeach;?></div></div><?php endif;?>
<form method="post" class="content-card form-card" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>">
<div class="form-grid">
<div class="field"><label for="first_name">First name <span class="required">*</span></label><input id="first_name" name="first_name" type="text" required autocomplete="given-name" value="<?=e((string)($_POST['first_name']??''))?>"></div>
<div class="field"><label for="last_name">Last name <span class="required">*</span></label><input id="last_name" name="last_name" type="text" required autocomplete="family-name" value="<?=e((string)($_POST['last_name']??''))?>"></div>
<div class="field"><label for="email">Email <span class="required">*</span></label><input id="email" name="email" type="email" required autocomplete="email" value="<?=e((string)($_POST['email']??''))?>"></div>
<div class="field"><label for="role_id">Role <span class="required">*</span></label><select id="role_id" name="role_id" required><option value="">Select a role</option><?php foreach($roles as $role):$rid=(int)($role['id']??0);?><option value="<?=e((string)$rid)?>" <?=((int)($_POST['role_id']??0)===$rid)?'selected':''?>><?=e((string)($role['name']??'Role'))?></option><?php endforeach;?></select><?php if(!$roles):?><small class="muted">No roles available. Create a role first.</small><?php endif;?></div>
<div class="field"><label for="department_id">Department</label><select id="department_id" name="department_id"><option value="">No department assigned</option><?php foreach($departments as $department):$did=(int)($department['id']??0);?><option value="<?=e((string)$did)?>" <?=((int)($_POST['department_id']??0)===$did)?'selected':''?>><?=e((string)($department['name']??''))?></option><?php endforeach;?></select><small class="field-help">This department will be used to automatically preselect the user's department when creating visits and gatepasses.</small></div></div><div class="alert alert-info"><strong>Initial password:</strong> <code>PassNow@123</code>. The user will be required to change it immediately after their first successful login.</div><div class="form-actions"><a class="btn btn-secondary" href="<?=e(url('users.php'))?>">Cancel</a><button class="btn btn-primary" type="submit" data-loading-label="Creating..."><span data-button-label>Create user</span></button></div>
</form>
