<section class="page-header"><div><span class="eyebrow">Settings · Visits</span><h1><?= $id ? 'Edit' : 'Add' ?> visit type</h1><p>Configure the categories users can select when registering or scheduling visits.</p></div><a class="btn btn-secondary" href="<?=e(url('visit-types.php'))?>"><i class="fa-solid fa-arrow-left"></i> Back</a></section>
<?php if($errors):?><div class="alert alert-danger"><div><?php foreach($errors as $x):?><div><?=e($x)?></div><?php endforeach;?></div></div><?php endif;?>
<form method="post" class="content-card form-card settings-type-form" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>">
 <div class="form-section"><h2>Visit type details</h2><p class="muted">Codes are used internally while names and descriptions help users choose the correct category.</p><div class="form-grid">
  <div class="field"><label for="name">Name <span class="required">*</span></label><input id="name" name="name" required maxlength="100" value="<?=e((string)($item['name']??''))?>" placeholder="e.g. Business Meeting"></div>
  <div class="field"><label for="code">Code <span class="required">*</span></label><input id="code" name="code" required maxlength="30" value="<?=e((string)($item['code']??''))?>" placeholder="e.g. BUSINESS_MEETING" data-uppercase><small class="field-help">Short unique identifier for this visit category.</small></div>
  <div class="field field-full"><label for="description">Description</label><textarea id="description" name="description" rows="4" maxlength="255" placeholder="Explain when this visit type should be used."><?=e((string)($item['description']??''))?></textarea></div>
  <div class="field field-full"><label class="checkbox-row"><input type="checkbox" name="active" value="1" <?=!array_key_exists('active',$item)||!empty($item['active'])?'checked':''?>><span><strong>Type is active</strong><br><small>Inactive visit types remain on historical records but cannot be selected for new visits.</small></span></label></div>
 </div></div>
 <div class="form-actions"><a class="btn btn-secondary" href="<?=e(url('visit-types.php'))?>">Cancel</a><button class="btn btn-primary" type="submit" data-loading-label="Saving..."><span data-button-label>Save visit type</span></button></div>
</form><script>document.querySelector('[data-uppercase]')?.addEventListener('input',e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,'_'));</script>