<section class="page-header"><div><span class="eyebrow">Visits</span><h1>New visit</h1><p>Schedule an appointment or check in a walk-in visitor immediately.</p></div><a class="btn btn-secondary" data-back href="<?=e(url('visits.php'))?>"><i class="fa-solid fa-arrow-left"></i> Back</a></section>
<?php if($errors): ?><div class="alert alert-danger"><div><?php foreach($errors as $x): ?><div><?=e($x)?></div><?php endforeach;?></div></div><?php endif;?>
<form method="post" class="content-card form-card" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>">
<div class="card-header"><h2>Visit details</h2><p>All selectable values are loaded from the current tenant database.</p></div>
<div class="form-grid"><div class="field field-full"><label>Visit entry</label><div class="segmented-control"><label><input type="radio" name="entry_source" value="pre_registered" checked> Pre-registered</label><label><input type="radio" name="entry_source" value="walk_in"> Walk-in</label></div><small class="field-help" id="entry_source_help">Pre-register an upcoming visitor before arrival.</small></div>
<div class="field field-full"><label for="visitor_search">Visitor <span class="required">*</span></label><input id="visitor_search" type="search" autocomplete="off" placeholder="Search by name, ID, phone or email"><input type="hidden" id="visitor_id" name="visitor_id" required><div id="visitor_results" class="search-results" hidden></div><small class="field-help">Search and select an existing visitor. Registration is handled separately to avoid duplicate visitor profiles.</small><select id="visitor_id_legacy" hidden aria-hidden="true"><option value="">Select visitor</option><?php foreach($visitors as $visitor): $name=(string)($visitor['full_name']??trim((string)($visitor['first_name']??'').' '.(string)($visitor['last_name']??'')));?><option value="<?=e((string)($visitor['id']??''))?>" <?=((int)($visitor['id']??0)===$preselectedVisitor)?'selected':''?>><?=e($name)?></option><?php endforeach;?></select></div>
<?php component('select',['name'=>'visit_type_id','label'=>'Visit type','options'=>$types,'value'=>(string)oldOr('visit_type_id'),'required'=>true]);?>
<div class="field"><label for="department_id">Department</label><select id="department_id" name="department_id"><option value="">No department</option><?php $selectedDepartment=(string)oldOr('department_id',$currentDepartmentID!==null?(string)$currentDepartmentID:'');foreach($departments as $department):$did=(int)($department['id']??0);?><option value="<?=e((string)$did)?>" <?=($selectedDepartment===(string)$did)?'selected':''?>><?=e((string)($department['name']??''))?></option><?php endforeach;?></select><?php if($currentDepartmentID):?><small class="field-help">Preselected from your user department.</small><?php endif;?></div>
<div class="field"><label for="host_name">Host employee</label><select id="host_name" name="host_name"><option value="">Select host</option><?php foreach($employees as $employee):$name=trim((string)($employee['first_name']??'').' '.(string)($employee['last_name']??''));?><option value="<?=e($name)?>" <?=((string)oldOr('host_name')===$name)?'selected':''?>><?=e($name!==''?$name:(string)($employee['employee_number']??'Employee'))?></option><?php endforeach;?></select></div>
<?php component('field',['name'=>'expected_time','label'=>'Expected arrival','type'=>'datetime-local','value'=>(string)oldOr('expected_time')]);?><?php component('field',['name'=>'expected_departure_at','label'=>'Expected departure','type'=>'datetime-local','value'=>(string)oldOr('expected_departure_at')]);?>
<?php component('textarea',['name'=>'purpose','label'=>'Purpose','value'=>(string)oldOr('purpose'),'required'=>true,'maxlength'=>500,'placeholder'=>'Reason for the visit']);?>
<div class="field field-full"><label class="checkbox-row"><input type="checkbox" name="check_in_now" value="1" <?=isset($_POST['check_in_now'])?'checked':''?>><span><strong>Check in immediately</strong><br><small>Creates the visit, records arrival and issues a badge in one operation.</small></span></label></div>
</div><div class="form-actions"><a class="btn btn-secondary" data-back href="<?=e(url('visits.php'))?>">Cancel</a><button class="btn btn-primary" type="submit" data-loading-label="Creating..."><span data-button-label>Create visit</span></button></div>
</form>
<script>
(()=>{const search=document.getElementById('visitor_search'),id=document.getElementById('visitor_id'),results=document.getElementById('visitor_results'),legacy=document.getElementById('visitor_id_legacy');let timer,seq=0;const pick=v=>{id.value=v.id;search.value=v.full_name||('Visitor #'+v.id);results.hidden=true;results.innerHTML='';};const run=async()=>{const q=search.value.trim();if(q.length<2){results.hidden=true;return}const current=++seq;try{const r=await fetch('/api/v1/visitors?q='+encodeURIComponent(q)+'&limit=10',{headers:{Accept:'application/json'}});const data=await r.json();if(current!==seq)return;const items=data.items||data.data?.items||[];results.innerHTML='';items.forEach(v=>{const b=document.createElement('button');b.type='button';b.className='search-result';b.textContent=(v.full_name||'Visitor')+(v.id_number?' • '+v.id_number:'')+(v.phone?' • '+v.phone:'');b.onclick=()=>pick(v);results.appendChild(b)});results.hidden=!items.length}catch(_){results.hidden=true}};search.addEventListener('input',()=>{id.value='';clearTimeout(timer);timer=setTimeout(run,250)});legacy.addEventListener('change',()=>{const o=legacy.selectedOptions[0];if(o&&o.value)pick({id:o.value,full_name:o.textContent})});})();
</script>