<section class="page-header"><div><span class="eyebrow">Visits</span><h1>New visit</h1><p>Schedule an appointment or check in a walk-in visitor immediately.</p></div><a class="btn btn-secondary" data-back href="<?=e(url('visits.php'))?>"><i class="fa-solid fa-arrow-left"></i> Back</a></section>
<?php if($errors): ?><div class="alert alert-danger"><div><?php foreach($errors as $x): ?><div><?=e($x)?></div><?php endforeach;?></div></div><?php endif;?>
<form method="post" class="content-card form-card" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>">
<div class="card-header"><h2>Visit details</h2><p>All selectable values are loaded from the current tenant database.</p></div>
<div class="form-grid">
<div class="field"><label for="visitor_id">Visitor <span class="required">*</span></label><select id="visitor_id" name="visitor_id" required><option value="">Select visitor</option><?php foreach($visitors as $visitor): $name=(string)($visitor['full_name']??trim((string)($visitor['first_name']??'').' '.(string)($visitor['last_name']??'')));?><option value="<?=e((string)($visitor['id']??''))?>" <?=((int)($visitor['id']??0)===$preselectedVisitor)?'selected':''?>><?=e($name)?></option><?php endforeach;?></select></div>
<?php component('select',['name'=>'visit_type_id','label'=>'Visit type','options'=>$types,'value'=>(string)oldOr('visit_type_id'),'required'=>true]);?>
<?php component('select',['name'=>'department_id','label'=>'Department','options'=>$departments,'value'=>(string)oldOr('department_id')]);?>
<div class="field"><label for="host_name">Host employee</label><select id="host_name" name="host_name"><option value="">Select host</option><?php foreach($employees as $employee):$name=trim((string)($employee['first_name']??'').' '.(string)($employee['last_name']??''));?><option value="<?=e($name)?>" <?=((string)oldOr('host_name')===$name)?'selected':''?>><?=e($name!==''?$name:(string)($employee['employee_number']??'Employee'))?></option><?php endforeach;?></select></div>
<?php component('field',['name'=>'expected_time','label'=>'Expected arrival','type'=>'datetime-local','value'=>(string)oldOr('expected_time')]);?>
<?php component('textarea',['name'=>'purpose','label'=>'Purpose','value'=>(string)oldOr('purpose'),'required'=>true,'maxlength'=>500,'placeholder'=>'Reason for the visit']);?>
<div class="field field-full"><label class="checkbox-row"><input type="checkbox" name="check_in_now" value="1" <?=isset($_POST['check_in_now'])?'checked':''?>><span><strong>Check in immediately</strong><br><small>Creates the visit, records arrival and issues a badge in one operation.</small></span></label></div>
</div><div class="form-actions"><a class="btn btn-secondary" data-back href="<?=e(url('visits.php'))?>">Cancel</a><button class="btn btn-primary" type="submit" data-loading-label="Creating..."><span data-button-label>Create visit</span></button></div>
</form>
