<?php $status=strtolower((string)($visit['status']??''));$canIn=!empty($visit['can_check_in']);$canOut=!empty($visit['can_check_out']);$canCancel=!empty($visit['can_cancel']); ?>
<section class="page-header"><div><span class="eyebrow">Visit</span><h1><?=e((string)($visit['badge_number']??$visit['visitor_name']??'Visit'))?></h1><p><?=e((string)($visit['purpose']??'Visit details'))?></p></div><a class="btn btn-secondary" data-back href="<?=e(url('visits.php'))?>"><i class="fa-solid fa-arrow-left"></i> Back</a></section>
<?php if($error): ?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<?php if($visit && !empty($visit['overstayed'])): ?><div class="alert alert-warning"><i class="fa-solid fa-clock"></i> This visitor is still on premises after the expected visit time.</div><?php endif;?>
<?php if($visit): ?><section class="content-card"><div class="card-header detail-header"><div><h2>Visit information</h2><p>Current visit state and gate lifecycle.</p></div><span class="status-badge status-<?=e(preg_replace('/[^a-z0-9_-]/i','-',$status))?>"><?=e($visit['status']??'Unknown')?></span></div>
<dl class="detail-list"><?php foreach(['Visitor'=>$visit['visitor_name']??'—','Host'=>$visit['host_name']??'—','Department'=>$visit['department_name']??'—','Type'=>$visit['visit_type_name']??'—','Purpose'=>$visit['purpose']??'—','Expected'=>$visit['expected_time']??'—','Check-in'=>$visit['checked_in_at']??'—','Check-out'=>$visit['checked_out_at']??'—','Badge'=>$visit['badge_number']??'—'] as $k=>$v):?><div><dt><?=e($k)?></dt><dd><?=e((string)$v)?></dd></div><?php endforeach;?></dl>
<div class="form-actions">
<?php if($canIn): ?><form method="post" action="<?=e(url('visit-operation.php'))?>" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="id" value="<?=e((string)$id)?>"><input type="hidden" name="operation" value="check-in"><button class="btn btn-primary" data-loading-label="Checking in..."><span data-button-label>Check in</span></button></form><?php endif;?>
<?php if($canOut): ?><form method="post" action="<?=e(url('visit-operation.php'))?>" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="id" value="<?=e((string)$id)?>"><input type="hidden" name="operation" value="check-out"><button class="btn btn-primary" data-loading-label="Checking out..."><span data-button-label>Check out</span></button></form><?php endif;?>
<?php if($canCancel): ?><form method="post" action="<?=e(url('visit-operation.php'))?>" data-loading-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="id" value="<?=e((string)$id)?>"><input type="hidden" name="operation" value="cancel"><div class="field"><label for="reason">Cancellation reason</label><input id="reason" name="reason" required maxlength="255"></div><button class="btn btn-danger" data-loading-label="Cancelling..."><span data-button-label>Cancel visit</span></button></form><?php endif;?>
</div></section><?php endif;?>
